version: '3.8'
services:
  biletim-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: yarn start:dev
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - biletim-network
    restart: unless-stopped
  db:
    image: postgres:14
    container_name: db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - db-mem:/var/lib/postgresql/data
    networks:
      - biletim-network
volumes:
  db-mem:
    name: db-mem
networks:
  biletim-network:
    name: biletim-network