services:
  biletim-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: >
      sh -c "pnpm migration:run && pnpm start:dev"
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - biletim-db
      - biletim-redis
    networks:
      - biletim-network
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      # - ./open-zst.script.ts:/app/open-zst.script.ts
      # - ./feed_en_v3.json.zst:/app/feed_en_v3.json.zst
      # - ./hotels.json:/app/hotels.json
 
  biletim-db:
    image: postgres:15
    container_name: biletim-db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - biletim-vol:/var/lib/postgresql/data
    networks:
      - biletim-network
 
  biletim-redis:
    image: redis:6
    container_name: biletim-redis
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
    networks:
      - biletim-network
    volumes:
      - biletim-redis-vol:/data
    command: ["redis-server", "--appendonly", "yes"]
 

  biletim-redis:
    image: redis:6
    container_name: biletim-redis
    restart: always
    ports:
      - 6379:6379
    env_file:
      - .env
    networks:
      - biletim-network
    volumes:
      - biletim-redis-vol:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  biletim-vol:
    name: biletim-vol
  biletim-redis-vol:
    name: biletim-redis-vol


networks:
  biletim-network:
    name: biletim-network