version: '3.8'
services:
  biletim-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: yarn start:dev
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - biletim-db
    env_file:
      - .env
    networks:
      - biletim-network
    restart: unless-stopped
    volumes:
      - ./src:/app/src

  biletim-db:
    image: postgres:15
    container_name: biletim-db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - biletim-vol:/var/lib/postgresql/data
    networks:
      - biletim-network

volumes:
  biletim-vol:
    name: biletim-vol
networks:
  biletim-network:
    name: biletim-network
