services:
  biletim-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: >
      sh -c "pnpm migration:run && pnpm start:dev"
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - biletim-db
      - biletim-redis
      - biletim-chromium
    networks:
      - biletim-network
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./test:/app/test
 
  biletim-db:
    image: postgres:15
    container_name: biletim-db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - biletim-vol:/var/lib/postgresql/data
    networks:
      - biletim-network

  biletim-redis:
    image: redis:6
    container_name: biletim-redis
    restart: always
    ports:
      - 6379:6379
    env_file:
      - .env
    networks:
      - biletim-network
    volumes:
      - biletim-redis-vol:/data
    command: ["redis-server", "--appendonly", "yes"]
  
  biletim-chromium:
    build:
      context: ../biletim_chromium
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - biletim-network

  biletim-pgadmin:
    container_name: biletim-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - biletim-network
    restart: unless-stopped

volumes:
  pgadmin:
  biletim-vol:
    name: biletim-vol
  biletim-redis-vol:
    name: biletim-redis-vol


networks:
  biletim-network:
    name: biletim-network