FROM debian:bullseye-slim

# Set environment to avoid prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update && apt-get install -y \
    wget \
    ca-certificates \
    fonts-liberation \
    libappindicator3-1 \
    libx11-xcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxrandr2 \
    libxss1 \
    libasound2 \
    libatk1.0-0 \
    libcups2 \
    libnss3 \
    libnspr4 \
    libxshmfence1 \
    libgbm-dev \
    xdg-utils \
    chromium \
    --no-install-recommends

# Expose the port for Puppeteer
EXPOSE 9222

# Start Chromium in remote debugging mode
CMD ["chromium", "--headless", "--disable-gpu", "--no-sandbox", "--disable-software-rasterizer", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222"]
