services:
  biletim-backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: >
      sh -c "pnpm start:dev"
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - biletim-db
      - biletim-redis
      - biletim-chromium
      - biletim-mongodb
    networks:
      - biletim-network
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./test:/app/test

  biletim-chromium:
    build:
      context: ../biletim-chromium
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - biletim-network

  biletim-db:
    image: postgres:15
    container_name: biletim-db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - biletim-vol:/var/lib/postgresql/data
    networks:
      - biletim-network

  biletim-redis:
    image: redis:6
    container_name: biletim-redis
    restart: always
    ports:
      - 6379:6379
    env_file:
      - .env
    networks:
      - biletim-network
    volumes:
      - biletim-redis-vol:/data
    command: ['redis-server', '--appendonly', 'yes']

  biletim-mongodb:
    image: mongo:6.0
    restart: always
    container_name: biletim-mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - biletim-mongo-vol:/data/db
    networks:
      - biletim-network

volumes:
  pgadmin:
  biletim-vol:
    name: biletim-vol
  biletim-redis-vol:
    name: biletim-redis-vol
  biletim-mongo-vol:
    name: biletim-mongo-vol

networks:
  biletim-network:
    name: biletim-network
