export default {
  DATABASE: { POSTGRESQL: 'postgresql' },
  APPLICATION: 'application',
  AUTH: 'auth',
  SUPER_ADMIN: 'super_admin',
  BILET_ALL_API: 'bilet_all_api',
  HOTEL_API: 'hotel_api',
  QUEUE: 'queue',
  NETGSM: 'netgsm',
  SWAGGER: 'swagger',
  LOGIN_WITH_GOOGLE: 'login_with_google',
  LOGIN_WITH_FACEBOOK: 'login_with_facebook',
  NOTIFICATIONS: 'notifications',
  PAYMENT: 'payment',
  TAMAMLIYO_API: 'tamamliyo_api',
  CHROMIUM: 'chromium',
  MAILEON: 'maileon',
};
