nameOverride: ''
fullnameOverride: ''

chartVersion: ''
releaseName: 'biletim-api'
targetNamespace: 'default'
chartName: 'biletim-api'

global:
  imagePullSecrets:
    - registry-harbor

  ingress:
    enabled: true
    class:
    domain: westerops.com
    sslRedirect: true

certs:
  managed: true
  issuerName: letsencrypt-prod

biletim_api:
  enabled: true
  replicas: 1
  #nameSuffix: backend
  hostPrefix: biletimapi
  app: biletim-api
  port: 8080
  image: harbor.westerops.com/biletim/api:vIMAGE_TAG
  resources:
    limits:
      memory: 1Gi
      cpu: 500m
    requests:
      memory: 10Mi
      cpu: 10m
  # configMapName: finance-aggregator-miniapp-api-config
  env:
    APP_PORT: 8080
    NODE_ENV: development
    BACKEND_URL: https://biletimapi.westerops.com
    SUPER_ADMIN_EMAIL: super_admin@gmail.com
    SUPER_ADMIN_PASSWORD: SuperAdmin.12345
    SUPER_ADMIN_KEY: biletimcom2024
    JWT_SECRET: PEMPassPhrase
    JWT_EXPIRATION: 172800
    BCRYPT_SALT_ROUNDS: 12
    RESET_PASSWORD_URL: https://biletimlanding.westerops.com/tr

    # services
    CHOROMIUM_HOST: biletim-chromium
    CHOROMIUM_PORT: 9222

    # queue
    REDIS_HOST: biletim-redis
    REDIS_PORT: 6379
    REDIS_PASSWORD: 'my-password'

    # OAuth
    GOOGLE_OAUTH_CLIENT_ID: 347389858095-q2bqpat4bphrt778h8qfuepcd0tbt5o2.apps.googleusercontent.com
    GOOGLE_OAUTH_CLIENT_SECRET: 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
    FACEBOOK_OAUTH_CLIENT_ID: 372069605916295
    FACEBOOK_OAUTH_CLIENT_SECRET: 93aab68e49875d748c594c1721653309

    # DB
    DATABASE_URL: postgres://biletim-user:1234@biletim-db:5432/biletim?connect_timeout=300
    POSTGRES_USER: biletim-user
    POSTGRES_PASSWORD: 1234
    POSTGRES_HOST: biletim-db
    POSTGRES_PORT: 5432
    POSTGRES_DB: biletim

    MONGO_HOST: biletim-mongo
    MONGO_PORT: 27017
    MONGO_DB: biletim
    MONGO_USER: admin
    MONGO_PASSWORD: password

    # ticket
    BILETALL_BASE_URI: http://94.55.20.137/WSTEST/Service.asmx
    BILETALL_USERNAME: biletimcomWS
    BILETALL_PASSWORD: aa8809

    # hotel
    HOTEL_API_BASE_URL: https://api.worldota.net/api/b2b/v3
    HOTEL_WS_USERNAME: 8175
    HOTEL_WS_PASSWORD: 88346326-e817-4e3f-8852-44185a44e606

    # payment
    VAKIF_BANK_VPOS_BASE_URI: https://onlineodemetest.vakifbank.com.tr:4443
    VAKIF_BANK_3DS_BASE_URI: https://3dsecuretest.vakifbank.com.tr:4443
    VAKIF_BANK_MERCHANT_ID: '000100000013506'
    VAKIF_BANK_MERCHANT_PASSWORD: '123456'
    VAKIF_BANK_TERMINAL_NO: 'VP000579'

    BILETALL_3DS_BASE_URI: http://94.55.20.137//WSTEST/3DSecure/SecurePay2.aspx

    GARANTI_VPOS_BASE_URI: https://gbtaksimtunel-integration.garanti.com.tr
    GARANTI_SWITCH_ID: CC82C381E078482AB328943FCCB7100C
    GARANTI_SWITCH_PASSWORD: '123asdASD@'

    # insurance
    TAMAMLIYO_API_BASE_URL: https://api-test.tamamliyo.com
    TAMAMLIYO_TOKEN: b1bd655bcd0b061c32b2e8072f298769

    # notifications
    NETGSM_BASE_URL: 'https://api.netgsm.com.tr'
    NETGSM_USERNAME: '3626060962'
    NETGSM_PASSWORD: '41914FA'
    NETGSM_APP_KEY: 'xxx'

    EMAIL_USERNAME: dws.timetracker@gmail.com
    EMAIL_PASSWORD: 'zyyj jrjl syft egjh'
    EMAIL_PORT: 465
    EMAIL_HOST: smtp.gmail.com
    EMAIL_USE_SSL: 'true'
    EMAIL_FROM: 'info@westerops.com'

  volumeMounts:
    biletim-api: '/app/images'

  volumes:
    - name: biletim-api
      persistentVolumeClaim:
        claimName: biletim-api-pvc

biletim_db:
  enabled: true
  replicas: 1
  app: biletim-db
  port: 5432
  image: postgres:15.7
  # configMapName: finance-aggregator-miniapp-db-config
  env:
    POSTGRES_USER: biletim-user
    POSTGRES_PASSWORD: 1234
    POSTGRES_HOST: biletim-db
    POSTGRES_PORT: 5432
    POSTGRES_DB: biletim

  volumeMounts:
    db-data: '/var/lib/postgresql/data'

  volumes:
    - name: db-data
      persistentVolumeClaim:
        claimName: biletim-api-pvc

  resources:
    limits:
      memory: 1Gi
      cpu: 500m
    requests:
      memory: 10Mi
      cpu: 10m

ingress:
  tlsSecret: biletim-api-tls
  hostLabel: biletim-api-api
