nameOverride: ''
fullnameOverride: ''

chartVersion: ''
releaseName: 'biletim-api'
targetNamespace: 'default'
chartName: 'biletim-api'

global:
  imagePullSecrets:
    - registry-harbor

  ingress:
    enabled: true
    class:
    domain: westerops.com
    sslRedirect: true

certs:
  managed: true
  issuerName: letsencrypt-prod

biletim_api:
  enabled: true
  replicas: 1
  #nameSuffix: backend
  hostPrefix: biletimapi
  app: biletim-api
  port: 8080
  image: harbor.westerops.com/biletim/api:vIMAGE_TAG
  resources:
    limits:
      memory: 1Gi
      cpu: 500m
    requests:
      memory: 10Mi
      cpu: 10m
  # configMapName: finance-aggregator-miniapp-api-config
  env:
    APP_PORT: 8080
    NODE_ENV: development
    POSTGRES_USER: biletim-user
    POSTGRES_PASSWORD: 1234
    POSTGRES_HOST: biletim-db
    POSTGRES_PORT: 5432
    POSTGRES_DB: biletim
    DATABASE_URL: postgres://biletim-user:1234@biletim-db:5432/biletim?connect_timeout=300
    SUPER_ADMIN_EMAIL: super_admin@gmail.com
    SUPER_ADMIN_PASSWORD: SuperAdmin.12345
    SUPER_ADMIN_KEY: biletimcom2024
    JWT_SECRET: PEMPassPhrase
    JWT_EXPIRATION: 172800
    BCRYPT_SALT_ROUNDS: 12
    RESET_PASSWORD_URL: https://timetracker.westerops.com/reset-password
    BILETALL_BASE_URI: http://94.55.20.137/WSTEST/Service.asmx
    BILETALL_3DSECURE_BASE_URI: http://94.55.20.137//WSTEST/3DSecure/SecurePay2.aspx
    BILETALL_WS_USERNAME: biletimcomWS
    BILETALL_WS_PASSWORD: aa8809
    HOTEL_API_BASE_URL: https://api.worldota.net/api/b2b/v3
    HOTEL_WS_USERNAME: 8175
    HOTEL_WS_PASSWORD: 88346326-e817-4e3f-8852-44185a44e606
    EMAIL_USERNAME: dws.timetracker@gmail.com
    EMAIL_PASSWORD: 'zyyj jrjl syft egjh'
    EMAIL_PORT: 465
    EMAIL_HOST: smtp.gmail.com
    GOOGLE_OAUTH_CLIENT_ID: 347389858095-q2bqpat4bphrt778h8qfuepcd0tbt5o2.apps.googleusercontent.com
    GOOGLE_OAUTH_CLIENT_SECRET: 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
    FACEBOOK_OAUTH_CLIENT_ID: 372069605916295
    FACEBOOK_OAUTH_CLIENT_SECRET: 93aab68e49875d748c594c1721653309

  volumeMounts:
    biletim-api: '/app/images'

  volumes:
    - name: biletim-api
      persistentVolumeClaim:
        claimName: biletim-api-pvc

biletim_db:
  enabled: true
  replicas: 1
  app: biletim-db
  port: 5432
  image: postgres:15.7
  # configMapName: finance-aggregator-miniapp-db-config
  env:
    POSTGRES_USER: biletim-user
    POSTGRES_PASSWORD: 1234
    POSTGRES_HOST: biletim-db
    POSTGRES_PORT: 5432
    POSTGRES_DB: biletim

  volumeMounts:
    db-data: '/var/lib/postgresql/data'

  volumes:
    - name: db-data
      persistentVolumeClaim:
        claimName: biletim-api-pvc

  resources:
    limits:
      memory: 1Gi
      cpu: 500m
    requests:
      memory: 10Mi
      cpu: 10m

ingress:
  tlsSecret: biletim-api-tls
  hostLabel: biletim-api-api
