 {{- if .Values.biletim_redis.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.biletim_redis.app }}-pv
  labels:
    app: {{ .Values.biletim_redis.app }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.biletim_redis.storage | default "5Gi" }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/data/redis'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.biletim_redis.app }}-pvc
  labels:
    app: {{ .Values.biletim_redis.app }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.biletim_redis.storage | default "5Gi" }}
{{- end }}