import { BoardingPointDto } from '@app/modules/tickets/bus/dto/bus-boarding-point.dto';
import { BusCompanyDto } from '@app/modules/tickets/bus/dto/bus-company.dto';
import { BusRouteDetailDto } from '@app/modules/tickets/bus/dto/bus-route.dto';
import { BusSeatAvailabilityDto } from '@app/modules/tickets/bus/dto/bus-seat-availability.dto';
import { ServiceInformationDto } from '@app/modules/tickets/bus/dto/bus-service-information.dto';
import { BusTerminalDto } from '@app/modules/tickets/bus/dto/bus-terminal.dto';

export const busCompanyMockResponse: BusCompanyDto[] = [
  {
    companyNumber: '37',
    companyName: 'İnci Turizm',
    companyLogo: 'https://eticket.ipektr.com/wsbos3/LogoVer.Aspx?fnum=37',
    emptyBranchCode: '32011',
    emptyUserCode: '32011',
    ticketSerialNumberTracking: '0',
    ticketSerialNumber: '0',
    website: 'http://eticket.ipektr.com/Firms_37/',
    phone: '0 352 444 44 38',
    soldSeatCount: '100',
    reservedSeatCount: '100',
    companyNumberStr: '37',
    maxSameMemberCardTransactionInBus: '255',
    canPerformMultiGenderTransaction: '1',
    cancellationPeriodUntilDepartureMinutes: '60',
    isTicketCancellationActive: '1',
    isOpenMoneyUsageActive: '1',
  },
];

export const getBusTerminalsByNameMockResponse: BusTerminalDto[] = [
  {
    id: '1640',
    cityId: '5',
    countryCode: 'AL',
    region: null,
    name: 'Tiran (Arnavutluk)',
    description: null,
    isCenter: true,
    affiliatedCenterId: '0',
    appearInSearch: true,
  },
  {
    id: '1404',
    cityId: '304',
    countryCode: 'AZ',
    region: null,
    name: 'Bakü (Azerbaycan)',
    description: null,
    isCenter: true,
    affiliatedCenterId: '0',
    appearInSearch: true,
  },
  {
    id: '1429',
    cityId: '305',
    countryCode: 'AZ',
    region: null,
    name: 'Gence (Azerbaycan)',
    description: null,
    isCenter: true,
    affiliatedCenterId: '0',
    appearInSearch: true,
  },
  {
    id: '1665',
    cityId: '495',
    countryCode: 'BG',
    region: null,
    name: 'Aytos (Bulgaristan)',
    description: null,
    isCenter: true,
    affiliatedCenterId: '0',
    appearInSearch: true,
  },
  {
    id: '1667',
    cityId: '495',
    countryCode: 'BG',
    region: null,
    name: 'Burgaz (Bulgaristan)',
    description: null,
    isCenter: true,
    affiliatedCenterId: '0',
    appearInSearch: true,
  },
];

export const departureScheduleListMockResponse = {
  departureSchedulesAndFeatures: {
    schedulesAndFeatures: [
      {
        schedule: {
          id: '1',
          timeOfDay: 'Gece',
          companyNumber: '37',
          companyName: 'İnci Turizm',
          localTime: '2024-10-15T10:30:00+03:00',
          localInternetTime: '2024-10-15T10:30:00+03:00',
          date: '2024-10-15T00:00:00+03:00',
          time: '1900-01-01T10:30:00+03:00',
          dayEnd: '0',
          routeNumber: '3',
          initialDeparturePlace: 'ANKARA',
          finalArrivalPlace: 'KAYSERİ',
          departurePlace: 'ANKARA',
          arrivalPlace: 'KAYSERİ',
          initialDeparturePointId: '84',
          initialDeparturePoint: 'Ankara (Aşti)',
          departurePointId: '84',
          departurePoint: 'Ankara (Aşti)',
          arrivalPointId: '738',
          arrivalPoint: 'Kayseri',
          finalArrivalPointId: '738',
          finalArrivalPoint: 'Kayseri',
          busType: 'TR15',
          busSeatArrangementType: '2+2',
          busTypeDescription: 'Travego 15 SHD',
          busPhone: '(536)-633-33-36',
          busPlate: '',
          travelDuration: undefined,
          travelDurationDisplayType: '1',
          approximateTravelDuration: '5-6',
          ticketPrice1: '40',
          internetTicketPrice: '40',
          classDifference: '0',
          maxReservationTime: '0',
          tripType: '',
          tripTypeDescription: 'MOLALI',
          routeTripNumber: '',
          busTypeClass: '0',
          tripTrackingNumber: '21590',
          totalSaleCount: '0',
          occupancyRuleExists: '0',
          busTypeFeature: '00000000000000000000000000000000000000000000000000',
          normalTicketPrice: '40',
          isFullTrip: '0',
          facilities: '',
          tripAvailableSeatCount: '44',
          departureTerminalName: '',
          departureTerminalNameTimes: '',
          maximumReserveDateTime: '2024-10-14T00:00:00+03:00',
          route: 'Ankara (Aşti) ->Kayseri ',
          isCardRequired: 'false',
          isTicketCancellationActive: '1',
          isOpenMoneyUsageActive: '1',
          cancellationPeriodUntilDepartureMinutes: '60',
          companyTripDescription: '',
          isSalesRedirected: '0',
          seatSelectionAvailable: 'true',
          tripCode: '',
        },
        features: [],
      },
      {
        schedule: {
          id: '2',
          timeOfDay: 'Gece',
          companyNumber: '37',
          companyName: 'İnci Turizm',
          localTime: '2024-10-15T15:00:00+03:00',
          localInternetTime: '2024-10-15T15:00:00+03:00',
          date: '2024-10-15T00:00:00+03:00',
          time: '1900-01-01T15:00:00+03:00',
          dayEnd: '0',
          routeNumber: '3',
          initialDeparturePlace: 'ANKARA',
          finalArrivalPlace: 'KAYSERİ',
          departurePlace: 'ANKARA',
          arrivalPlace: 'KAYSERİ',
          initialDeparturePointId: '84',
          initialDeparturePoint: 'Ankara (Aşti)',
          departurePointId: '84',
          departurePoint: 'Ankara (Aşti)',
          arrivalPointId: '738',
          arrivalPoint: 'Kayseri',
          finalArrivalPointId: '738',
          finalArrivalPoint: 'Kayseri',
          busType: 'TR15',
          busSeatArrangementType: '2+2',
          busTypeDescription: 'Travego 15 SHD',
          busPhone: '(536)-633-33-36',
          busPlate: '',
          travelDuration: undefined,
          travelDurationDisplayType: '1',
          approximateTravelDuration: '5-6',
          ticketPrice1: '40',
          internetTicketPrice: '40',
          classDifference: '0',
          maxReservationTime: '0',
          tripType: '',
          tripTypeDescription: 'MOLALI',
          routeTripNumber: '',
          busTypeClass: '0',
          tripTrackingNumber: '21595',
          totalSaleCount: '0',
          occupancyRuleExists: '0',
          busTypeFeature: '00000000000000000000000000000000000000000000000000',
          normalTicketPrice: '40',
          isFullTrip: '0',
          facilities: '',
          tripAvailableSeatCount: '46',
          departureTerminalName: '',
          departureTerminalNameTimes: '',
          maximumReserveDateTime: '2024-10-14T00:00:00+03:00',
          route: 'Ankara (Aşti) ->Kayseri ',
          isCardRequired: 'false',
          isTicketCancellationActive: '1',
          isOpenMoneyUsageActive: '1',
          cancellationPeriodUntilDepartureMinutes: '60',
          companyTripDescription: '',
          isSalesRedirected: '0',
          seatSelectionAvailable: 'true',
          tripCode: '',
        },
        features: [],
      },
      {
        schedule: {
          id: '3',
          timeOfDay: 'Gece',
          companyNumber: '37',
          companyName: 'İnci Turizm',
          localTime: '2024-10-15T20:00:00+03:00',
          localInternetTime: '2024-10-15T20:00:00+03:00',
          date: '2024-10-15T00:00:00+03:00',
          time: '1900-01-01T20:00:00+03:00',
          dayEnd: '0',
          routeNumber: '3',
          initialDeparturePlace: 'ANKARA',
          finalArrivalPlace: 'KAYSERİ',
          departurePlace: 'ANKARA',
          arrivalPlace: 'KAYSERİ',
          initialDeparturePointId: '84',
          initialDeparturePoint: 'Ankara (Aşti)',
          departurePointId: '84',
          departurePoint: 'Ankara (Aşti)',
          arrivalPointId: '738',
          arrivalPoint: 'Kayseri',
          finalArrivalPointId: '738',
          finalArrivalPoint: 'Kayseri',
          busType: 'TR15',
          busSeatArrangementType: '2+2',
          busTypeDescription: 'Travego 15 SHD',
          busPhone: '(536)-633-33-36',
          busPlate: '',
          travelDuration: undefined,
          travelDurationDisplayType: '1',
          approximateTravelDuration: '5-6',
          ticketPrice1: '40',
          internetTicketPrice: '40',
          classDifference: '0',
          maxReservationTime: '0',
          tripType: '',
          tripTypeDescription: 'MOLALI',
          routeTripNumber: '',
          busTypeClass: '0',
          tripTrackingNumber: '21599',
          totalSaleCount: '0',
          occupancyRuleExists: '0',
          busTypeFeature: '00000000000000000000000000000000000000000000000000',
          normalTicketPrice: '40',
          isFullTrip: '0',
          facilities: '',
          tripAvailableSeatCount: '46',
          departureTerminalName: '',
          departureTerminalNameTimes: '',
          maximumReserveDateTime: '2024-10-14T00:00:00+03:00',
          route: 'Ankara (Aşti) ->Kayseri ',
          isCardRequired: 'false',
          isTicketCancellationActive: '1',
          isOpenMoneyUsageActive: '1',
          cancellationPeriodUntilDepartureMinutes: '60',
          companyTripDescription: '',
          isSalesRedirected: '0',
          seatSelectionAvailable: 'true',
          tripCode: '',
        },
        features: [],
      },
      {
        schedule: {
          id: '4',
          timeOfDay: 'Gece',
          companyNumber: '37',
          companyName: 'İnci Turizm',
          localTime: '2024-10-15T22:00:00+03:00',
          localInternetTime: '2024-10-15T22:00:00+03:00',
          date: '2024-10-15T00:00:00+03:00',
          time: '1900-01-01T22:00:00+03:00',
          dayEnd: '0',
          routeNumber: '3',
          initialDeparturePlace: 'ANKARA',
          finalArrivalPlace: 'KAYSERİ',
          departurePlace: 'ANKARA',
          arrivalPlace: 'KAYSERİ',
          initialDeparturePointId: '84',
          initialDeparturePoint: 'Ankara (Aşti)',
          departurePointId: '84',
          departurePoint: 'Ankara (Aşti)',
          arrivalPointId: '738',
          arrivalPoint: 'Kayseri',
          finalArrivalPointId: '738',
          finalArrivalPoint: 'Kayseri',
          busType: 'TR15',
          busSeatArrangementType: '2+2',
          busTypeDescription: 'Travego 15 SHD',
          busPhone: '(536)-633-33-36',
          busPlate: '',
          travelDuration: undefined,
          travelDurationDisplayType: '1',
          approximateTravelDuration: '5-6',
          ticketPrice1: '40',
          internetTicketPrice: '40',
          classDifference: '0',
          maxReservationTime: '0',
          tripType: '',
          tripTypeDescription: 'MOLALI',
          routeTripNumber: '',
          busTypeClass: '0',
          tripTrackingNumber: '21602',
          totalSaleCount: '0',
          occupancyRuleExists: '0',
          busTypeFeature: '00000000000000000000000000000000000000000000000000',
          normalTicketPrice: '40',
          isFullTrip: '0',
          facilities: '',
          tripAvailableSeatCount: '46',
          departureTerminalName: '',
          departureTerminalNameTimes: '',
          maximumReserveDateTime: '2024-10-14T00:00:00+03:00',
          route: 'Ankara (Aşti) ->Kayseri ',
          isCardRequired: 'false',
          isTicketCancellationActive: '1',
          isOpenMoneyUsageActive: '1',
          cancellationPeriodUntilDepartureMinutes: '60',
          companyTripDescription: '',
          isSalesRedirected: '0',
          seatSelectionAvailable: 'true',
          tripCode: '',
        },
        features: [],
      },
    ],
  },
};
export const returnScheduleListMockResponse = {
  returnSchedulesAndFeatures: {
    schedulesAndFeatures: [
      {
        schedule: {
          id: '1',
          timeOfDay: 'Gece',
          companyNumber: '37',
          companyName: 'İnci Turizm',
          localTime: '2024-10-15T10:30:00+03:00',
          localInternetTime: '2024-10-15T10:30:00+03:00',
          date: '2024-10-15T00:00:00+03:00',
          time: '1900-01-01T10:30:00+03:00',
          dayEnd: '0',
          routeNumber: '3',
          initialDeparturePlace: 'ANKARA',
          finalArrivalPlace: 'KAYSERİ',
          departurePlace: 'ANKARA',
          arrivalPlace: 'KAYSERİ',
          initialDeparturePointId: '84',
          initialDeparturePoint: 'Ankara (Aşti)',
          departurePointId: '84',
          departurePoint: 'Ankara (Aşti)',
          arrivalPointId: '738',
          arrivalPoint: 'Kayseri',
          finalArrivalPointId: '738',
          finalArrivalPoint: 'Kayseri',
          busType: 'TR15',
          busSeatArrangementType: '2+2',
          busTypeDescription: 'Travego 15 SHD',
          busPhone: '(536)-633-33-36',
          busPlate: '',
          travelDuration: undefined,
          travelDurationDisplayType: '1',
          approximateTravelDuration: '5-6',
          ticketPrice1: '40',
          internetTicketPrice: '40',
          classDifference: '0',
          maxReservationTime: '0',
          tripType: '',
          tripTypeDescription: 'MOLALI',
          routeTripNumber: '',
          busTypeClass: '0',
          tripTrackingNumber: '21590',
          totalSaleCount: '0',
          occupancyRuleExists: '0',
          busTypeFeature: '00000000000000000000000000000000000000000000000000',
          normalTicketPrice: '40',
          isFullTrip: '0',
          facilities: '',
          tripAvailableSeatCount: '44',
          departureTerminalName: '',
          departureTerminalNameTimes: '',
          maximumReserveDateTime: '2024-10-14T00:00:00+03:00',
          route: 'Ankara (Aşti) ->Kayseri ',
          isCardRequired: 'false',
          isTicketCancellationActive: '1',
          isOpenMoneyUsageActive: '1',
          cancellationPeriodUntilDepartureMinutes: '60',
          companyTripDescription: '',
          isSalesRedirected: '0',
          seatSelectionAvailable: 'true',
          tripCode: '',
        },
        features: [],
      },
      {
        schedule: {
          id: '2',
          timeOfDay: 'Gece',
          companyNumber: '37',
          companyName: 'İnci Turizm',
          localTime: '2024-10-15T15:00:00+03:00',
          localInternetTime: '2024-10-15T15:00:00+03:00',
          date: '2024-10-15T00:00:00+03:00',
          time: '1900-01-01T15:00:00+03:00',
          dayEnd: '0',
          routeNumber: '3',
          initialDeparturePlace: 'ANKARA',
          finalArrivalPlace: 'KAYSERİ',
          departurePlace: 'ANKARA',
          arrivalPlace: 'KAYSERİ',
          initialDeparturePointId: '84',
          initialDeparturePoint: 'Ankara (Aşti)',
          departurePointId: '84',
          departurePoint: 'Ankara (Aşti)',
          arrivalPointId: '738',
          arrivalPoint: 'Kayseri',
          finalArrivalPointId: '738',
          finalArrivalPoint: 'Kayseri',
          busType: 'TR15',
          busSeatArrangementType: '2+2',
          busTypeDescription: 'Travego 15 SHD',
          busPhone: '(536)-633-33-36',
          busPlate: '',
          travelDuration: undefined,
          travelDurationDisplayType: '1',
          approximateTravelDuration: '5-6',
          ticketPrice1: '40',
          internetTicketPrice: '40',
          classDifference: '0',
          maxReservationTime: '0',
          tripType: '',
          tripTypeDescription: 'MOLALI',
          routeTripNumber: '',
          busTypeClass: '0',
          tripTrackingNumber: '21595',
          totalSaleCount: '0',
          occupancyRuleExists: '0',
          busTypeFeature: '00000000000000000000000000000000000000000000000000',
          normalTicketPrice: '40',
          isFullTrip: '0',
          facilities: '',
          tripAvailableSeatCount: '46',
          departureTerminalName: '',
          departureTerminalNameTimes: '',
          maximumReserveDateTime: '2024-10-14T00:00:00+03:00',
          route: 'Ankara (Aşti) ->Kayseri ',
          isCardRequired: 'false',
          isTicketCancellationActive: '1',
          isOpenMoneyUsageActive: '1',
          cancellationPeriodUntilDepartureMinutes: '60',
          companyTripDescription: '',
          isSalesRedirected: '0',
          seatSelectionAvailable: 'true',
          tripCode: '',
        },
        features: [],
      },
      {
        schedule: {
          id: '3',
          timeOfDay: 'Gece',
          companyNumber: '37',
          companyName: 'İnci Turizm',
          localTime: '2024-10-15T20:00:00+03:00',
          localInternetTime: '2024-10-15T20:00:00+03:00',
          date: '2024-10-15T00:00:00+03:00',
          time: '1900-01-01T20:00:00+03:00',
          dayEnd: '0',
          routeNumber: '3',
          initialDeparturePlace: 'ANKARA',
          finalArrivalPlace: 'KAYSERİ',
          departurePlace: 'ANKARA',
          arrivalPlace: 'KAYSERİ',
          initialDeparturePointId: '84',
          initialDeparturePoint: 'Ankara (Aşti)',
          departurePointId: '84',
          departurePoint: 'Ankara (Aşti)',
          arrivalPointId: '738',
          arrivalPoint: 'Kayseri',
          finalArrivalPointId: '738',
          finalArrivalPoint: 'Kayseri',
          busType: 'TR15',
          busSeatArrangementType: '2+2',
          busTypeDescription: 'Travego 15 SHD',
          busPhone: '(536)-633-33-36',
          busPlate: '',
          travelDuration: undefined,
          travelDurationDisplayType: '1',
          approximateTravelDuration: '5-6',
          ticketPrice1: '40',
          internetTicketPrice: '40',
          classDifference: '0',
          maxReservationTime: '0',
          tripType: '',
          tripTypeDescription: 'MOLALI',
          routeTripNumber: '',
          busTypeClass: '0',
          tripTrackingNumber: '21599',
          totalSaleCount: '0',
          occupancyRuleExists: '0',
          busTypeFeature: '00000000000000000000000000000000000000000000000000',
          normalTicketPrice: '40',
          isFullTrip: '0',
          facilities: '',
          tripAvailableSeatCount: '46',
          departureTerminalName: '',
          departureTerminalNameTimes: '',
          maximumReserveDateTime: '2024-10-14T00:00:00+03:00',
          route: 'Ankara (Aşti) ->Kayseri ',
          isCardRequired: 'false',
          isTicketCancellationActive: '1',
          isOpenMoneyUsageActive: '1',
          cancellationPeriodUntilDepartureMinutes: '60',
          companyTripDescription: '',
          isSalesRedirected: '0',
          seatSelectionAvailable: 'true',
          tripCode: '',
        },
        features: [],
      },
      {
        schedule: {
          id: '4',
          timeOfDay: 'Gece',
          companyNumber: '37',
          companyName: 'İnci Turizm',
          localTime: '2024-10-15T22:00:00+03:00',
          localInternetTime: '2024-10-15T22:00:00+03:00',
          date: '2024-10-15T00:00:00+03:00',
          time: '1900-01-01T22:00:00+03:00',
          dayEnd: '0',
          routeNumber: '3',
          initialDeparturePlace: 'ANKARA',
          finalArrivalPlace: 'KAYSERİ',
          departurePlace: 'ANKARA',
          arrivalPlace: 'KAYSERİ',
          initialDeparturePointId: '84',
          initialDeparturePoint: 'Ankara (Aşti)',
          departurePointId: '84',
          departurePoint: 'Ankara (Aşti)',
          arrivalPointId: '738',
          arrivalPoint: 'Kayseri',
          finalArrivalPointId: '738',
          finalArrivalPoint: 'Kayseri',
          busType: 'TR15',
          busSeatArrangementType: '2+2',
          busTypeDescription: 'Travego 15 SHD',
          busPhone: '(536)-633-33-36',
          busPlate: '',
          travelDuration: undefined,
          travelDurationDisplayType: '1',
          approximateTravelDuration: '5-6',
          ticketPrice1: '40',
          internetTicketPrice: '40',
          classDifference: '0',
          maxReservationTime: '0',
          tripType: '',
          tripTypeDescription: 'MOLALI',
          routeTripNumber: '',
          busTypeClass: '0',
          tripTrackingNumber: '21602',
          totalSaleCount: '0',
          occupancyRuleExists: '0',
          busTypeFeature: '00000000000000000000000000000000000000000000000000',
          normalTicketPrice: '40',
          isFullTrip: '0',
          facilities: '',
          tripAvailableSeatCount: '46',
          departureTerminalName: '',
          departureTerminalNameTimes: '',
          maximumReserveDateTime: '2024-10-14T00:00:00+03:00',
          route: 'Ankara (Aşti) ->Kayseri ',
          isCardRequired: 'false',
          isTicketCancellationActive: '1',
          isOpenMoneyUsageActive: '1',
          cancellationPeriodUntilDepartureMinutes: '60',
          companyTripDescription: '',
          isSalesRedirected: '0',
          seatSelectionAvailable: 'true',
          tripCode: '',
        },
        features: [],
      },
    ],
  },
};

export const busSearchMockResponse = {
  trip: {
    localDateTime: '2024-09-15T15:00:00+03:00',
    internetDateTime: '2024-09-15T15:00:00+03:00',
    departureName: 'ANKARA',
    arrivalName: 'KAYSERİ',
    routeNumber: '3',
    priceChangeable: 'False',
    ticketPrice1: '40.00',
    ticketPrice2: '0.00',
    ticketPrice3: '0.00',
    internetTicketPrice: '40.00',
    classDifferenceTicketPrice: '0.00',
    singleSeatDifferenceTicketPrice: '0.00',
    guestTicketPrice: '0.01',
    sellsGuestTickets: 'false',
    sellsDiscountedTicketsForDisabled: 'false',
    sellsQuotaTickets: 'true',
    isReservationActive: 'true',
    isSaleActive: 'true',
    maximumReservationDateTime: '14.09.2024 15:00:00',
    busType: 'TR15',
    busTypeClass: '0',
    busTypeSecondFloorRow: '0',
    busPlate: '',
    busCaptainName: '',
    busHostessName: '',
    departureTime: '0',
    busTripMessage: '',
    busBranchMessage: '',
    platformNumber: '',
    departureTerminalName: '',
    nightDescription: 'Pazar',
    maximumEmptyFemaleSeats: '3',
    branchTicketPort: '1',
    totalPassengerPoints: '0',
    passengerPointsMultiplier: '1,0000',
    occupancyRateDiscountApplied: 'False',
    busTypeFeature: '00000000000000000000000000000000000000000000000000',
    backwardSeats: '',
    idNumberRequiredForBranchSale: '1',
    travelDuration: '1.01.1900 05:00:00',
    tripTypeDescription: 'MOLALI',
    busTypeDescription: 'Travego 15 SHD',
    companyBestPriceActive: '0',
    busMessage:
      '%3cfont+style%3d%27font-family%3aVerdana%3bfont-size%3a11px%3bfont-weight%3a700%3btext-decoration%3aunderline%2cfalse%3bcolor%3a%23333%3bmargin%3a1px%3b%27%3e%3cb%3e%c4%b0%c5%9fleminiz%2c+Kredi+Kart%c4%b1+Hesap+Ekstrenizde%3cbr%3e%5bB%c4%b0LETAL+%c4%b0%c3%87+VE+DI%c5%9e+T%c4%b0C%5d+olarak+g%c3%b6r%c3%bcnecektir.%3c%2fb%3e%3c%2ffont%3e',
    facilities: '',
    payment3DSecureActive: '1',
    payment3DSecureMandatory: '1',
    paypalUpperLimit: '500',
    maximumEmptyMaleSeats: '5',
    sellableSeatCount: '48',
    reservationCannotBeMadeReason: '',
    companyMaxTotalTicketPrice: '10000.0000',
    canProcessWithPassportNumber: '1',
    canSelectSeatsOfDifferentGenders: '1',
    busSeatLayout: '',
    busHESCodeMandatory: '0',
    doubleSeatCanBeSoldToSinglePassenger: '1',
    singleSeatsFullDoubleSeatsSalePossible: '1',
    approximateTravelDuration: '',
    travelDurationDisplayType: '1',
    canSelectSeatsWithDifferentPrices: '1',
    ticketCancellationActive: '1',
    openMoneyUsageActive: '1',
    cancellationTimeUntilDepartureMinutes: '60',
    departurePointID: '84',
    departurePoint: 'Ankara (Aşti)',
    arrivalPointID: '738',
    arrivalPoint: 'Kayseri',
  },
  seats: [
    {
      seatString: '01',
      seatNumber: '1',
      status: '0',
      adjacentStatus: '0',
      internetSeatPrice: '40',
    },
    {
      seatString: '02',
      seatNumber: '2',
      status: '0',
      adjacentStatus: '0',
      internetSeatPrice: '40',
    },
  ],
  travelTypes: [
    {
      travelType: '0',
      travelName: 'Normal',
      ticketPrice: '40',
      ticketPriceClassDifference: '0',
      singleSeatPriceDifference: '0',
    },
    {
      travelType: '1',
      travelName: 'Özürlü',
      ticketPrice: '0',
      ticketPriceClassDifference: '0',
      singleSeatPriceDifference: '0',
    },
  ],
  features: [
    {
      typeFeature: '0',
      typeFeatureDescription: 'İnternet',
      typeFeatureDetail:
        'Sağladığımız internet bağlantısını bilgisayarınızda kullanabilirsiniz.',
      typeFeatureIcon: 'Internet.gif',
    },
    {
      typeFeature: '1',
      typeFeatureDescription: 'Rahat Koltuk',
      typeFeatureDetail: 'Bu araçta geniş ve rahat koltuk bulunmaktadır.',
      typeFeatureIcon: 'Rahat_Koltuk.gif',
    },
  ],
  paymentRules: {
    payment3DSecureActive: true,
    payment3DSecureMandatory: true,
    openMoneyPaymentActive: true,
    prePaymentActive: true,
    parakodPaymentActive: false,
    bkmPaymentActive: false,
    paypalPaymentActive: false,
    paymentRulePaypalUpperLimit: '500',
    hopiActive: false,
    masterpassActive: false,
    fastPayPaymentActive: false,
    garantiPayPaymentActive: false,
  },
};

export const busSeatAvailabilityMockResponse: BusSeatAvailabilityDto = {
  isAvailable: true,
};

export const boardingPointMockResponse: BoardingPointDto[] = [
  {
    time: '2018-12-10T02:30:00+03:00',
  },
  {
    place: '',
    time: '2018-12-10T02:30:00+03:00',
    visibleOnInternet: false,
  },
  {
    place: ' BELSİN GİRİŞ ',
    time: '2018-12-10T02:30:00+03:00',
    visibleOnInternet: true,
  },
  {
    place: ' FUZULİ',
    time: '2018-12-10T02:30:00+03:00',
    visibleOnInternet: true,
  },
  {
    place: ' HIMMETD SHEL',
    time: '2018-12-10T02:30:00+03:00',
    visibleOnInternet: true,
  },
  {
    place: ' TOYOTA',
    time: '2018-12-10T02:30:00+03:00',
    visibleOnInternet: true,
  },
  {
    place: 'AĞAÇ İŞLERİ',
    time: '2018-12-10T02:40:00+03:00',
    visibleOnInternet: true,
  },
];

export const serviceInformationMockResponse: ServiceInformationDto[] = [
  {
    place: 'ANAYURT 2',
    time: '2018-12-10T15:47:00+03:00',
    visibleOnInternet: true,
  },
];

export const getRouteMockResponse: BusRouteDetailDto[] = [
  {
    arrivalPlace: 'ANKARA',
    orderNumber: '3',
    departureDateTime: '1900-01-01T00:00:00+03:00',
    arrivalDateTime: '2024-08-05T18:00:00+03:00',
    routePointID: '84',
    routePointName: 'Ankara (Aşti)',
  },
  {
    arrivalPlace: 'KIRIKKALE',
    orderNumber: '4',
    departureDateTime: '1900-01-01T00:00:00+03:00',
    arrivalDateTime: '2024-08-05T19:00:00+03:00',
    routePointID: '1275',
    routePointName: 'Kırıkkale',
  },
  {
    arrivalDateTime: '2024-08-05T21:00:00+03:00',
    arrivalPlace: 'KIRŞEHİR',
    departureDateTime: '1900-01-01T00:00:00+03:00',
    orderNumber: '5',
    routePointID: '771',
    routePointName: 'Kırşehir',
  },
  {
    arrivalDateTime: '2024-08-05T23:00:00+03:00',
    arrivalPlace: 'KAYSERİ',
    departureDateTime: '1900-01-01T00:00:00+03:00',
    orderNumber: '6',
    routePointID: '738',
    routePointName: 'Kayseri',
  },
];

export const saleRequestMockResponse = {
  IslemSonuc: {
    Sonuc: 'true',
    PNR: 'GC03037',
    Mesaj: '',
    SeferInternetTarihSaat: '2018-12-10T02:30:00',
    Ebilet1: '037011459532',
  },
};
