apiVersion: v1
kind: PersistentVolume
metadata:
  name: biletim-api-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/postgresql/biletim-api-db/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: biletim-api-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: biletim-api-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/app/biletim-api"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: biletim-api-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi