nameOverride: ''
fullnameOverride: ''

chartVersion: ''
releaseName: 'biletim-backend'
targetNamespace: 'default'
chartName: 'biletim-backend'

global:
  imagePullSecrets:
    - ecr-secret

  ingress:
    sslRedirect: true
    tlsSecret: biletim-tls
    timeout: 120
    acmeChallengeType: 'dns01'
    acmeDNS01Provider: 'route53'

certs:
  managed: true
  issuerName: letsencrypt-route53

biletim_backend:
  app: biletim-backend
  port: 8080
  resources:
    limits:
      memory: 1Gi
      cpu: 500m
    requests:
      memory: 10Mi
      cpu: 10m

biletim_redis:
  app: biletim-redis
  port: 6379
  image: redis:6.0
  storage: 5Gi
  resources:
    limits:
      memory: 1Gi
      cpu: 500m
    requests:
      memory: 10Mi
      cpu: 10m
  command:
    - redis-server
    - --requirepass
    - $(REDIS_PASSWORD)
    - --appendonly
    - "yes"
