{{- if .Values.biletim_api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.biletim_api.app }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.biletim_api.port }}
    targetPort: {{ .Values.biletim_api.port }}
  selector:
    app: {{ .Values.biletim_api.app }}
{{- end }}


